Acknowledge Incident In PagerDuty
port-labs/self-service-actions-examples pull request #14
Opened 2024-02-19 10:56 UTC by mk-armah

Added github action to enable acknowlegment of pagerduty incident from port
This action takes `from` as input parameter and leverages incident details present in port to update pagerduty incident status to acknowleged

## Inputs
| Name                 | Description                                                                                          | Required | Default            |
|----------------------|------------------------------------------------------------------------------------------------------|----------|--------------------
| from              | The email address of a valid user associated with the account making the request.                                                              | true    | -               |

2024-02-22 10:52 UTC, yairsimantov20 requested changes
Left comments
Also please resolve conflicts

2024-02-22 10:52 UTC, yairsimantov20 commented on github-workflows/pagerduty/README.md
> +          logMessage: "Entity upserting was successful ✅"
Can you also make sure to send a log for a failure?

2024-02-22 10:52 UTC, yairsimantov20 commented on github-workflows/pagerduty/README.md
> +          logMessage: "Entity upserting was successful ✅"
Can you also make sure to send a log for a failure?

2024-02-22 10:52 UTC, yairsimantov20 commented on github-workflows/pagerduty/README.md
> +      - name: Inform execution of request to change incident owner
```suggestion
    steps:
      - name: Inform execution of request to change incident owner
```

2024-02-22 10:52 UTC, yairsimantov20 commented on github-workflows/pagerduty/README.md
> +        uses: port-labs/port-github-action@v1
```suggestion
    steps:
      - name: Log Executing Request to Acknowledge Incident
        uses: port-labs/port-github-action@v1
```

2024-02-22 10:52 UTC, yairsimantov20 commented on github-workflows/pagerduty/README.md
> +          general context (blueprint, run id, etc...)
Inputs are set to required but you are not validating it
github wont validate it for you

2024-02-22 10:52 UTC, yairsimantov20 commented on github-workflows/pagerduty/README.md
> +          general context (blueprint, run id, etc...)
Inputs are set to required but you are not validating it
github wont validate it for you

2024-02-26 09:01 UTC, mk-armah commented on github-workflows/pagerduty/README.md
> +          general context (blueprint, run id, etc...)
How about Port's validation ?

2024-03-17 17:46 UTC, closed without merging