Added Examples for AWS EC2, PagerDuty Service and PagerDuty Incident
port-labs/self-service-actions-examples pull request #2
Opened 2024-01-18 07:38 UTC by mk-armah

## Update

- [ ] Added GitHub action examples for Triggering a PagerDuty Incident 
- [ ] Added examples for creating a PagerDuty Service.
- [ ] Added examples for creating an EC2 Instance using Terraform

2024-01-18 09:51 UTC, PeyGis requested changes

2024-01-18 09:51 UTC, PeyGis commented on github-workflows/aws/README.md
> +3. Create a blueprint for EC2 Instance [learn more](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/#:~:text=EC2%20instance%20blueprint])
Instead of referring the user to the blueprint schema, add the blueprint json schema here.

2024-01-18 09:51 UTC, PeyGis commented on github-workflows/aws/README.md
> +      ec2-name:
Can you make sure the name of the properties are aligned? in the action and blueprint, you have `ec2_name`. But in the workflow input you're using `ec2-name`

2024-01-18 09:51 UTC, PeyGis commented on github-workflows/aws/README.md
> +        "ec_2_name": {
change to ec2_name. make sure to update the other field accordingly

2024-01-18 09:51 UTC, PeyGis commented on github-workflows/aws/README.md
> +          aws-region: us-east-1
The AWS region should be passed as an environment variable

2024-01-18 09:51 UTC, PeyGis commented on github-workflows/aws/README.md
> +          cd tf-example/ec2/
The name of your folder is **terraform-examples** but you're cd-ing into **tf-example**

2024-01-18 09:51 UTC, PeyGis commented on github-workflows/aws/README.md
> +    owners = ["099720109477"] # Canonical
What's this ID for?

2024-01-18 10:49 UTC, PeyGis requested changes

2024-01-18 10:49 UTC, PeyGis commented on github-workflows/pagerduty/README.md
> +        "escalation_policy_id"
make the service name required

2024-01-18 10:49 UTC, PeyGis commented on github-workflows/pagerduty/README.md
> +            - name: Create a log message
You should have a step that comes before this... Just like the other ones... it should log to Port that it's about to create a Pagerduty service

2024-01-18 10:49 UTC, PeyGis commented on github-workflows/pagerduty/README.md
> +             PagerDuty service created! ✅
Since this is a create invocation type, can you also UPSERT the entity to Port if possible?

2024-01-19 16:32 UTC, PeyGis commented on github-workflows/aws/README.md
> +    owners = ["099720109477"] # Canonical
Thanks for clarifying that

2024-01-19 16:33 UTC, mk-armah commented on github-workflows/aws/README.md
> +    owners = ["099720109477"] # Canonical
This account ID is the same for anyone who wants to use the official Ubuntu AMIs in AWS, regardless of their personal or organizational AWS account.

2024-01-29 11:01 UTC, MatanHeledPort approved these changes
LGTM

2024-01-29 12:04 UTC, merged