Github action to compute Dora metrics for a service
port-labs/self-service-actions-examples pull request #20
Opened 2024-02-26 14:59 UTC by mk-armah

Github action computes dora metrics for a service (repo)

## Inputs
| Name                 | Description                                                                                          | Required | Default            |
|----------------------|------------------------------------------------------------------------------------------------------|----------|--------------------|
| repository              | GitHub repository in owner/repo format eg. port-labs/self-service-actions                               | true     | -                  |
| timeframe              | Time frame in weeks to calculate metrics on                                                              | true    | -               |

2024-02-29 16:18 UTC, awconstable commented
Look forward to using this

2024-03-11 19:21 UTC, Tankilevitch requested changes

2024-03-11 19:21 UTC, Tankilevitch commented on github-workflows/github/src/calculate_pr_metrics.py
> +
overall in python I prefer that we use more descriptive parameter names.
```suggestion
        self.github_client = Github(os.getenv('GITHUB_TOKEN'))
        self.repo_name = repo_name
        self.time_frame = int(time_frame)
        self.start_date = datetime.utcnow().replace(tzinfo=timezone.utc) - timedelta(days=self.time_frame)
        self.repo = self.g.get_repo(f"{self.repo_name}")


```

2024-03-11 19:21 UTC, Tankilevitch commented on github-workflows/github/dora-metrics.yaml
> +          pip install PyGithub datetime
create `requirements.txt` containing those versions and install it

2024-03-11 19:21 UTC, Tankilevitch commented on github-workflows/github/README.md
> +[![Slack](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)](https://join.slack.com/t/devex-community/shared_invite/zt-1bmf5621e-GGfuJdMPK2D8UN58qL4E_g)
update slack to port-community slack link

2024-03-11 19:21 UTC, Tankilevitch commented on github-workflows/github/dora-metrics.yaml
> +          $jsonLine = $output | Select-String "###JSON_START###" -Context 0,1 | ForEach-Object { $_.Context.PostContext }
I see that you are using both `secrets.PATTOKEN` and `secret.GITHUB_TOKEN` please explain why do we need both?

2024-03-11 19:21 UTC, Tankilevitch commented on github-workflows/github/dora-metrics.yaml
> +          identifier: "${{ fromJson(env.metrics).id }}"
where is the `env.metrics` is coming from? couldn't find it

2024-03-11 19:21 UTC, Tankilevitch commented on github-workflows/github/dora-metrics.yaml
> +        type: string
I think it is possible that the action will run scheduled in their environment and not from an action, make sure this is supported.

2024-03-11 19:21 UTC, Tankilevitch commented on github-workflows/github/src/calculate_pr_metrics.py
> +    time_frame = os.getenv('TIMEFRAME_IN_DAYS') #os.getenv('TIME_FRAME')
```suggestion
    time_frame = os.getenv('TIMEFRAME_IN_DAYS')

```

2024-03-12 17:06 UTC, PeyGis requested changes

2024-03-12 17:06 UTC, PeyGis commented on github-workflows/github/README.md
> +        "icon": "Github",a
There's a typo here

2024-03-12 17:06 UTC, PeyGis commented on github-workflows/github/README.md
> +    "org": "my-org",
update to `<your-org>`

2024-03-12 17:06 UTC, PeyGis commented on github-workflows/github/README.md
> +    "repo": "my-org",
update to `<your-repo>`

2024-03-12 21:57 UTC, mk-armah commented on github-workflows/github/dora-metrics.yaml
> +          identifier: "${{ fromJson(env.metrics).id }}"
Python Script

2024-03-28 09:13 UTC, closed without merging

2024-04-04 06:25 UTC, awconstable commented
Please can you explain why this was closed? Is there an alternative approach?