escalate incident in pagerduty
port-labs/self-service-actions-examples pull request #21
Opened 2024-02-27 10:17 UTC by mk-armah

This action enables escalating a PagerDuty incident from Port

## Inputs
| Name                 | Description                                                                                          | Required | Default            |
|----------------------|------------------------------------------------------------------------------------------------------|----------|--------------------|
| escalation_policy_id         | PagerDuty Escalation Policy ID to apply     | true    | -                  |
| urgency              |  New urgency level for the incident (e.g., "high")                                | true     | -                  |
| from              | The email address of a valid user associated with the account making the request.                                                              | true    | -               |

2024-02-27 11:25 UTC, PeyGis requested changes

2024-02-27 11:25 UTC, PeyGis commented on github-workflows/pagerduty/README.md
> +        "type": "string",
remove the comma

2024-02-27 11:25 UTC, PeyGis commented on github-workflows/pagerduty/README.md
> +        "type": "string",
remove the comma

2024-03-17 15:52 UTC, MPTG94 requested changes
Fix comments

2024-03-17 15:52 UTC, MPTG94 commented on github-workflows/pagerduty/README.md
> +# Escalate Incident In Pagerduty
```suggestion
# Escalate Incident In PagerDuty
```

2024-03-17 15:52 UTC, MPTG94 commented on github-workflows/pagerduty/README.md
> +## Quickstart - Escalate An Incident In Pagerduty
```suggestion
## Escalate An Incident In PagerDuty
```

2024-03-17 15:52 UTC, MPTG94 commented on github-workflows/pagerduty/README.md
> +2. Install the Ports GitHub app from [here](https://github.com/apps/getport-io/installations/new).
```suggestion
2. Install the Port GitHub app from [here](https://github.com/apps/getport-io/installations/new).
```

2024-03-17 15:52 UTC, MPTG94 commented on github-workflows/pagerduty/README.md
> +3. Install Port's pager duty integration [learn more](https://github.com/port-labs/Port-Ocean/tree/main/integrations/pagerduty)
```suggestion
3. Install Port's PagerDuty integration [learn more](https://github.com/port-labs/Port-Ocean/tree/main/integrations/pagerduty)
```

2024-03-17 15:52 UTC, MPTG94 commented on github-workflows/pagerduty/README.md
> +>**Note** This step is not required for this example, but it will create all the blueprint boilerplate for you, and also update the catalog in real time with the new incident created.
```suggestion
>**Note** The above step is not required for this example, but it will create all the blueprint boilerplate for you, and also update the catalog in real time with the new incident created.
```

2024-03-17 15:52 UTC, MPTG94 commented on github-workflows/pagerduty/README.md
> +>**Note** Replace the invocation method with your own repository details.
```suggestion
>**Note** In the `invocationMethod` section, replace the `org` and `repo` values with your own repository details
```

2024-03-17 15:52 UTC, MPTG94 commented on github-workflows/pagerduty/README.md
> +```yml
Do not paste the file content here, add a link to the file that is saved in the repository. Having the file twice will make maintenance difficult when changes are made

2024-03-28 09:12 UTC, closed without merging