PORT-6747 | Create github action that puts tag on sonarqube project
port-labs/self-service-actions-examples pull request #22
Opened 2024-02-29 09:50 UTC by lordsarcastic

Self service action to put tag on SonarQube project.

2024-03-01 12:22 UTC, PeyGis requested changes
LGTM. Left 2 minor comments

2024-03-01 12:22 UTC, PeyGis commented on github-workflows/sonarqube/add-tags-to-sonarqube-project.yml
> +        type: string
Add required:true to the tags input

2024-03-01 12:22 UTC, PeyGis commented on github-workflows/sonarqube/README.md
> +* `SONARQUBE_API_TOKEN` - SonarQube API token. This can be a Project Analysis token for the specific project, a Global Analysis token or a user token
Also mention that the token `Requires the following permission: 'Administer' rights on the specified project`

2024-03-17 15:59 UTC, MPTG94 requested changes
Fix comments

2024-03-17 15:59 UTC, MPTG94 commented on github-workflows/sonarqube/README.md
> +## Quickstart - Add tag to SonarQube project from the service catalog
```suggestion
## Add tag to SonarQube project from the service catalog
```

2024-03-17 15:59 UTC, MPTG94 commented on github-workflows/sonarqube/README.md
> +2. Install the Ports GitHub app from [here](https://github.com/apps/getport-io/installations/new).
```suggestion
2. Install the Port GitHub app from [here](https://github.com/apps/getport-io/installations/new).
```

2024-03-17 15:59 UTC, MPTG94 commented on github-workflows/sonarqube/README.md
> +>**Note** This step is not required for this example, but it will create all the blueprint boilerplate for you, and also update the catalog in real time with the new incident created.
```suggestion
>**Note** The above step is not required for this example, but it will create all the blueprint boilerplate for you, and also update the catalog in real time with the new incident created.
```

2024-03-17 15:59 UTC, MPTG94 commented on github-workflows/sonarqube/README.md
> +>**Note** Update the `invocationMethod` field with your own repository details.
```suggestion
>**Note** In the `invocationMethod` section, replace the `org` and `repo` values with your own repository details
```

2024-03-28 09:08 UTC, closed without merging