Show an example of how to trigger Incident in OpsGenie using using a github action
port-labs/self-service-actions-examples pull request #3
Opened 2024-01-19 05:24 UTC by lordsarcastic

2024-01-19 15:59 UTC, PeyGis requested changes
LGTM

2024-01-19 15:59 UTC, PeyGis commented on github-workflows/opsgenie/README.md
> +          "description": "escription field of the incident that is generally used to provide a detailed information about the incident.",
Typo in `escription`

2024-01-19 15:59 UTC, PeyGis commented on github-workflows/opsgenie/trigger-opsgenie-incident.yml
> +          url: "https://api.eu.opsgenie.com/v1/incidents/create"
I will actually prefer you use the default API location https://api.opsgenie.com instead of the EU API location

You will need to find a way to make this dynamic or add a comment that tells the user to change the url based on their region

2024-01-23 12:21 UTC, MatanHeledPort reviewed
LGTM just clean up

2024-01-23 12:21 UTC, MatanHeledPort commented on github-workflows/servicenow/README.md
Doesnt this file and the servicenow incidient exist in a different PR?

2024-01-23 12:22 UTC, lordsarcastic commented on github-workflows/servicenow/README.md
Yeah I branched off this branch in the other PR.

2024-01-23 12:23 UTC, MatanHeledPort commented on github-workflows/servicenow/README.md
ok!

2024-01-23 12:23 UTC, MatanHeledPort approved these changes
lgtm!

2024-01-23 12:24 UTC, MatanHeledPort approved these changes
lgtm

2024-01-23 12:30 UTC, lordsarcastic commented on github-workflows/servicenow/trigger-servicenow-incident.yml
> +      - name: Inform of workflow completion
What's a run link and where do I get it?

2024-01-29 15:45 UTC, merged