Add an resources for github-affecting workflows
port-labs/self-service-actions-examples pull request #7
Opened 2024-02-07 16:50 UTC by phalbert

Workflow for this [guide](https://github.com/port-labs/port-docs/pull/892)

2024-02-22 10:49 UTC, yairsimantov20 approved these changes
🌊

2024-02-22 10:49 UTC, yairsimantov20 requested changes
left a few comments

2024-02-22 11:13 UTC, yairsimantov20 requested changes
Left comments

2024-02-22 12:18 UTC, phalbert commented on github-workflows/aws/tag-aws-cli.yml
> +      run: sudo apt-get install jq
alright, thank you for pointing this out.

2024-02-23 10:38 UTC, phalbert commented on github-workflows/aws/tag-aws-cli.yml
> +        # }
Yes, I believe including a sample from the JSON object here can be beneficial for preemptively addressing potential questions about the expected object.

2024-02-23 10:55 UTC, phalbert commented on github-workflows/github/delete-repo.yml
> +            GitHub repository deleted! ✅
handled it now

2024-02-23 11:54 UTC, phalbert commented on github-workflows/github/manage-pr.yml
added these now

2024-02-23 11:55 UTC, phalbert commented on github-workflows/aws/tag-aws-cli.yml
Added this now

2024-02-23 11:56 UTC, phalbert commented on github-workflows/aws/tag-aws-cli.yml
> +        type: string
what do you mean here? I thought the `required: true` is the validation.

2024-02-23 11:56 UTC, phalbert commented on github-workflows/azure/tag-azure-cli.yml
alright

2024-03-17 12:29 UTC, MPTG94 requested changes
Please apply requested changes and comments from me and Yair and let me know when done

2024-03-28 12:36 UTC, phalbert commented
I have moved these actions to port-docs:

1. [Manage GitHub PRs](https://github.com/port-labs/port-docs/pull/1029)
2. [Add Tags to S3 bucket](https://github.com/port-labs/port-docs/pull/1031)
3. [Tag Azure Resource](https://github.com/port-labs/port-docs/pull/1030)

2024-03-28 12:36 UTC, closed without merging